services:
  minio1:
    image: bitnami/minio:2024.5.10
    container_name: minio1
    command: minio server --address ":9000" --console-address ":9001" http://minio{1...4}/bitnami/minio/data
    volumes:
      - minio1_data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DISTRIBUTED_MODE_ENABLED: yes
      MINIO_DISTRIBUTED_NODES: minio1, minio2, minio3, minio4
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SCHEME: http
      TZ: "America/Sao_Paulo"
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - minio-net

  minio2:
    image: bitnami/minio:2024.5.10
    container_name: minio2
    command: minio server --address ":9000" --console-address ":9001" http://minio{1...4}/bitnami/minio/data
    volumes:
      - minio2_data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DISTRIBUTED_MODE_ENABLED: yes
      MINIO_DISTRIBUTED_NODES: minio1, minio2, minio3, minio4
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SCHEME: http
      TZ: "America/Sao_Paulo"
    networks:
      - minio-net

  minio3:
    image: bitnami/minio:2024.5.10
    container_name: minio3
    command: minio server --address ":9000" --console-address ":9001" http://minio{1...4}/bitnami/minio/data
    volumes:
      - minio3_data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DISTRIBUTED_MODE_ENABLED: yes
      MINIO_DISTRIBUTED_NODES: minio1, minio2, minio3, minio4
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SCHEME: http
      TZ: "America/Sao_Paulo"
    networks:
      - minio-net

  minio4:
    image: bitnami/minio:2024.5.10
    container_name: minio4
    command: minio server --address ":9000" --console-address ":9001" http://minio{1...4}/bitnami/minio/data
    volumes:
      - minio4_data:/bitnami/minio/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DISTRIBUTED_MODE_ENABLED: yes
      MINIO_DISTRIBUTED_NODES: minio1, minio2, minio3, minio4
      MINIO_PROMETHEUS_URL: http://prometheus:9090
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SCHEME: http
      TZ: "America/Sao_Paulo"
    networks:
      - minio-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/philippe/minIO/servers/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge

volumes:
  minio1_data:
    driver: local
  minio2_data:
    driver: local
  minio3_data:
    driver: local
  minio4_data:
    driver: local
