global:
   scrape_interval: 60s

scrape_configs:
- job_name: minio-job
  bearer_token: <SEU-TOKEN>
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['minio1:9000']
