package com.fullstack.projeto;

public enum Tipos {
    MATRIZ_DE_DEMANDA_DE_CURSOS,
    MATRIZ_DE_DEMANDA_DE_GLOBAL,
    MATRIZ_DE_OFERTAS_DE_CURSOS,
    MATRIZ_DE_OFERTA_DE_SERVICOS,
    MATRIZ_DE_OFERTA_GLOBAL,
    MANIFESTACAO_DE_INTENCAO_DE_MINISTRAR_COMPONENTE_CURRICULAR,
    CONSOLIDACAO_DA_MATRIZ_DE_DEMANDA_GLOBAL_DA_UNIDADE_ACADEMICA,
    SEMESTRE_LETIVO,
    MATRIZ_DE_DEMANDA_DE_SERVICOS,
    AJUSTES_DA_MATRIZ_DE_OFERTAS_DE_CURSOS,
    AJUSTES_NA_MATRIZ_DE_OFERTAS_DE_SERVICOS,
    RESOLUCAO_DE_ANOMALIAS_NAS_OFERTAS_DE_COMPONENTES_CURRICULARES,
    OFERTAS_DE_TURMA_NO_SIGAA
}
